In [48]:
label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from scipy import stats
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from operator import itemgetter

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [49]:
df=pd.read_csv('train_gue5.csv')[:-341099] #POTONG DATA TRAINING
val_df=pd.read_csv('val_gue5.csv')

In [50]:
object_columns=list(df.loc[:, df.dtypes == object].columns); object_columns

didrop = list(object_columns)

didrop.append('returnQuantity')
didrop.append('colorCode')
df.rrp.fillna(df.rrp.median(), inplace=True)
val_df.rrp.fillna(df.rrp.median(), inplace=True)
didrop.append('productGroup')

X_train=df.drop(didrop, axis=1).values
X_val=val_df.drop(didrop, axis=1).values
y_train=df.returnQuantity.values
y_val=val_df.returnQuantity.values

In [59]:
model=LinearRegression(n_jobs=-1)
model.fit(X_train,y_train)
y_pred = model.predict(X_val)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
baseline_score = dmc_error(y_pred, y_val)
print baseline_score

print confusion_matrix(y_val,y_pred)
print 'jumlah data test: ', len(y_val)

 127372.0
[[101652  65240     27      0      0      0]
 [ 61341 112157     12      0      0      0]
 [    22    599      9      0      0      0]
 [     0     23      6      0      0      0]
 [     0      2      5      0      0      0]
 [     0      2      2      0      0      0]]
jumlah data test:  341099


In [57]:
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
model=ExtraTreesRegressor(n_jobs=-1)
model.fit(X_train,y_train)
y_pred = model.predict(X_val)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
etr_score = dmc_error(y_pred, y_val)
print etr_score

133602.0


In [53]:
n_features=X_train.shape[1]

support_ = np.ones(n_features, dtype=np.bool)
ranking_ = np.ones(n_features, dtype=np.int)
scores_ = []

for col_number in range(X_train.shape[1] ):
    
    print col_number
    
    # Remaining features
    features_ = np.arange(n_features)[support_]
    features = list( set(features_)-set([col_number]) )
    
    

    # Rank the remaining features
    estimator = LinearRegression(n_jobs=-1)

    estimator.fit(X_train[:, features], y_train)
    y_pred=estimator.predict(X_val[:, features])
    y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
    y_pred[y_pred<0]=0
    current_score= dmc_error(y_val, y_pred)
    print(current_score)
    scores_.append(current_score)

0
127429.0
1
127410.0
2
128907.0
3
127438.0
4
127378.0
5
127378.0
6
125840.0
7
128207.0
8
127434.0
9
127434.0
10
127434.0
11
127400.0
12
127408.0
13
127624.0
14
127398.0
15
127374.0
16
127438.0
17
127540.0
18
127353.0
19
132307.0
20
127621.0
21
128026.0
22
127392.0
23
127399.0
24
127399.0
25
127416.0
26
127383.0
27
127394.0
28
127386.0
29
127285.0
30
127397.0
31
127400.0
32
126618.0
33
127393.0
34
127315.0
35
127399.0
36
127198.0
37
127417.0
38
127393.0
39
127376.0
40
127421.0
41
127401.0


In [44]:
n_features=X_train.shape[1]

support_ = np.ones(n_features, dtype=np.bool)
ranking_ = np.ones(n_features, dtype=np.int)
scores_ = []

for col_number in range(X_train.shape[1] ):
    
    print col_number
    
    # Remaining features
    features_ = np.arange(n_features)[support_]
    features = list( set(features_)-set([col_number]) )

    # Rank the remaining features
    estimator = LinearRegression(n_jobs=-1)

    estimator.fit(X_train[:, features], y_train)
    y_pred=estimator.predict(X_val[:, features])
    y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
    y_pred[y_pred<0]=0
    current_score= dmc_error(y_val, y_pred)
    print(current_score)
    scores_.append(current_score)

0
127469.0
1
127400.0
2
128765.0
3
127469.0
4
127382.0
5
127383.0
6
125794.0
7
128253.0
8
127428.0
9
127428.0
10
127428.0
11
127398.0
12
127413.0
13
127642.0
14
127396.0
15
127344.0
16
127399.0
17
127552.0
18
127364.0
19
132277.0
20
127525.0
21
128071.0
22
127397.0
23
127396.0
24
127397.0
25
127419.0
26
127361.0
27
127392.0
28
127369.0
29
127331.0
30
127400.0
31
127400.0
32
126598.0
33
127397.0
34
127388.0
35
127397.0
36
127254.0
37
127418.0
38
127393.0
39
127406.0
40
127427.0
41
127367.0


In [38]:
Xdf=df.drop(didrop, axis=1)

In [54]:
[s for s in scores_ if s>127395]

[127429.0,
 127410.0,
 128907.0,
 127438.0,
 128207.0,
 127434.0,
 127434.0,
 127434.0,
 127400.0,
 127408.0,
 127624.0,
 127398.0,
 127438.0,
 127540.0,
 132307.0,
 127621.0,
 128026.0,
 127399.0,
 127399.0,
 127416.0,
 127397.0,
 127400.0,
 127399.0,
 127417.0,
 127421.0,
 127401.0]

In [56]:
from itertools import izip as zip

pair=zip(Xdf.columns, scores_)
t1=[i for i in pair]; t1
arai=sorted(t1, key=itemgetter(1)); arai

[('customer_budget', 125840.0),
 ('arcosi_prob', 126618.0),
 ('arsivo_prob', 127198.0),
 ('sipr_prob', 127285.0),
 ('arcovo_prob', 127315.0),
 ('voucherID_prob', 127353.0),
 ('colorCode_prob', 127374.0),
 ('cosivo_prob', 127376.0),
 ('voucherAmount', 127378.0),
 ('order_total', 127378.0),
 ('cosi_prob', 127383.0),
 ('covo_prob', 127386.0),
 ('arco_prob', 127392.0),
 ('arcopr_prob', 127393.0),
 ('cosipr_prob', 127393.0),
 ('copr_prob', 127394.0),
 ('sivo_prob', 127397.0),
 ('articleID_prob', 127398.0),
 ('arsi_prob', 127399.0),
 ('arpr_prob', 127399.0),
 ('arsipr_prob', 127399.0),
 ('after_voucher', 127400.0),
 ('prvo_prob', 127400.0),
 ('siprvo_prob', 127401.0),
 ('order_order', 127408.0),
 ('price', 127410.0),
 ('arvo_prob', 127416.0),
 ('arprvo_prob', 127417.0),
 ('coprvo_prob', 127421.0),
 ('deviceID', 127429.0),
 ('unit_price', 127434.0),
 ('median_unit_price', 127434.0),
 ('price_diff', 127434.0),
 ('rrp', 127438.0),
 ('sizeCode_prob', 127438.0),
 ('productGroup_prob', 127540.0),
