In [1]:
label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from scipy import stats
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from operator import itemgetter

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [2]:
df=pd.read_csv('train_gue5.csv')[:-341099] #POTONG DATA TRAINING
val_df=pd.read_csv('val_gue5.csv')

In [3]:
object_columns=list(df.loc[:, df.dtypes == object].columns); object_columns

didrop = list(object_columns)

didrop.append('returnQuantity')
didrop.append('colorCode')
df.rrp.fillna(df.rrp.median(), inplace=True)
val_df.rrp.fillna(df.rrp.median(), inplace=True)
didrop.append('productGroup')

X_train=df.drop(didrop, axis=1).values
X_val=val_df.drop(didrop, axis=1).values
y_train=df.returnQuantity.values
y_val=val_df.returnQuantity.values

In [88]:
model=LinearRegression(n_jobs=-1)
model.fit(X_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

In [89]:
y_pred_lr = model.predict(X_val)
y_pred_lr[y_pred_lr<0]=0
y_pred_lr_round=np.round(y_pred_lr).astype(np.int8)
baseline_score = dmc_error(y_pred_lr_round, y_val)
print baseline_score

print confusion_matrix(y_val,y_pred_lr_round)
print 'jumlah data test: ', len(y_val)

127371.0
[[101650  65242     27      0      0      0]
 [ 61338 112160     12      0      0      0]
 [    22    599      9      0      0      0]
 [     0     23      6      0      0      0]
 [     0      2      5      0      0      0]
 [     0      2      2      0      0      0]]
jumlah data test:  341099


### Kode ensembling dari Bahrun, mirip yang di Otto
### Tapi hasilnya JELEK. Kayanya ini untuk predict_proba, kayanya BUKAN untuk regresi

In [12]:
### Kode ensembling dari Bahrun, mirip yang di Otto
### Tapi hasilnya JELEK. Kayanya ini untuk predict_proba, kayanya BUKAN untuk regresi

from scipy.optimize import minimize
import numpy as np

def get_weights(y_true, predictions):

    def dmc_loss_func(weights):
        """scipy minimize will pass the weights as a numpy array"""
        final_prediction = 0
        for weight, prediction in zip(weights, predictions):
                final_prediction += weight * prediction
                
        #final_prediction= np.argmax(final_prediction,axis=1)
        return dmc_error(y_true, final_prediction)

    # the algorithms need a starting value, right not we chose average value for all weights
    # its better to choose many random starting points and run minimize a few times
    starting_values = np.ones(len(predictions)) / (len(predictions))

    # adding constraints  and a different solver as suggested by user 16universe
    # https://kaggle2.blob.core.windows.net/forum-message-attachments/75655/2393/otto%20model%20weights.pdf?sv=2012-02-12&se=2015-05-03T21%3A22%3A17Z&sr=b&sp=r&sig=rkeA7EJC%2BiQ%2FJ%2BcMpcA4lYQLFh6ubNqs2XAkGtFsAv0%3D
    cons = ({'type':'eq','fun':lambda w: 1-sum(w)})

    # our weights are bound between 0 and 1
    bounds = [(0,1)]*len(predictions)

    res = minimize(dmc_loss_func, starting_values, method='SLSQP', bounds=bounds, constraints=cons)
    return res

w1=get_weights(y_val, [y_pred_lr,y_pred_lr_round]);

# INI DIA
w1.x

array([  6.58406830e-05,   9.99934159e-01])

In [ ]:
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
model=RandomForestRegressor(n_jobs=-1)
model.fit(X_train,y_train)

In [34]:
y_pred_etr = model.predict(X_val)
y_pred_etr_round =np.round(y_pred_etr).astype(np.int8)
etr_score = dmc_error(y_val, y_pred_etr_round)
print etr_score

135683.0


In [26]:
w2=get_weights(y_val, [y_pred_lr,y_pred_etr]);

# INI DIA
w2.x

array([  1.15284522e-09,   9.99999999e-01])

In [37]:
ridge=Ridge()
ridge.fit(X_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [38]:
y_pred_ridge = ridge.predict(X_val)
y_pred_ridge[y_pred_ridge<0]=0
y_pred_ridge_round=np.round(y_pred_ridge).astype(np.int8)
ridge_score = dmc_error(y_pred_ridge_round, y_val)
print ridge_score

print confusion_matrix(y_val,y_pred_ridge_round)
print 'jumlah data test: ', len(y_val)

127435.0
[[101602  65290     27      0      0      0]
 [ 61354 112144     12      0      0      0]
 [    22    599      9      0      0      0]
 [     0     23      6      0      0      0]
 [     0      2      5      0      0      0]
 [     0      2      2      0      0      0]]
jumlah data test:  341099


In [90]:
w2=get_weights(y_val, [y_pred_lr_round, y_pred_etr_round,y_pred_ridge]);
ens2=np.round(w2.x[0] *y_pred_lr_round + w2.x[1] *y_pred_etr_round+w2.x[2]*y_pred_ridge_round).astype(np.int8)
ens3=np.round(w2.x[0] *y_pred_lr + w2.x[1] *y_pred_etr+w2.x[2]*y_pred_ridge).astype(np.int8);ens3

print dmc_error(y_val, y_pred_etr_round)
print dmc_error(y_val, y_pred_lr_round)
print dmc_error(y_val, ens2)
print dmc_error(y_val, ens3)

135683.0
127371.0
127371.0
127371.0


In [83]:
# Coba transformasi log sebelum regression ensembling, tapi malah sama aja atau jelek

p1=np.exp(y_pred_lr)-1
p2=np.exp(y_pred_etr)-1
p3=np.exp(y_pred_ridge)-1

w4=get_weights(np.exp(y_val)-1, [p1, p2, p3]);
ens4=np.log(w4.x[0]*p1 + w4.x[1]*p2 + w4.x[2]*p3 +1)

#
print 'ens4'
print dmc_error(y_val, ens4)
ens4=np.round(ens4)
print dmc_error(y_val, ens4)

#
print 'ens5'
# Sama ajaaa
ens5=(p1+p2+p3)/3
ens5=np.log(ens5+1)
print dmc_error(y_val, ens5)
ens5=np.round(ens5)
print dmc_error(y_val, ens5)

ens4
144013.8
131223.0
ens5
147330.587833
127806.0


In [95]:
enz=np.array([y_pred_lr_round, y_pred_etr_round,y_pred_ridge]).T; enz

array([[ 1.        ,  1.        ,  0.9407359 ],
       [ 1.        ,  1.        ,  0.93771455],
       [ 0.        ,  0.        ,  0.38455864],
       ..., 
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.12530515],
       [ 0.        ,  0.        ,  0.07683197]])

In [96]:
rfr_ensemble=RandomForestRegressor(n_jobs=-1)
rfr_ensemble.fit(enz,y_val)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=-1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [97]:
enz_pred=rfr_ensemble.predict(enz)

In [100]:
dmc_error(y_val, np.round(enz_pred))

22405.0

In [151]:
rfr_ensemble2=RandomForestRegressor(n_jobs=-1)
rfr_ensemble2.fit(enz[:170549],y_val[:170549])
enz_pred2=rfr_ensemble2.predict(enz[170549:])
dmc_error(y_val[170549:], np.round(enz_pred2))

76812.0

In [156]:
76812*2

153624

In [153]:
rfr_ensemble2=RandomForestRegressor(n_jobs=-1)
rfr_ensemble2.fit(enz[:255824],y_val[:255824])
enz_pred2=rfr_ensemble2.predict(enz[255824:])
dmc_error(y_val[255824:], np.round(enz_pred2))

38527.0

In [157]:
38527*4

154108

In [138]:
#confusion_matrix(y_val[170549:], np.round(enz_pred2[170549:]))
enz_pred2.shape

(170550L,)

In [101]:
lr_ensemble=LinearRegression(n_jobs=-1)
lr_ensemble.fit(enz,y_val)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

In [102]:
enz_pred_lr=lr_ensemble.predict(enz)

In [104]:
lr_ensemble.coef_

array([ 0.04465288,  0.0293414 ,  0.62152184])

In [105]:
lc=lr_ensemble.coef_

In [103]:
dmc_error(y_val, np.round(enz_pred_lr))

127068.0

In [117]:
enzlr=np.round(lc[0] *enz[:,0] + lc[1] *enz[:,1] +lc[2]*enz[:,2] ).astype(np.int8); enzlr

array([1, 1, 0, ..., 0, 0, 0], dtype=int8)

In [118]:
dmc_error(y_val, np.round(enzlr))

151599.0

In [154]:
lr_ensemble2=LinearRegression(n_jobs=-1)
lr_ensemble2.fit(enz[:170549],y_val[:170549])
enz_pred3=lr_ensemble2.predict(enz[170549:])
dmc_error(y_val[170549:], np.round(enz_pred3))

64915.0

In [155]:
64915*2

129830

In [ ]:
#Logit

In [158]:
logit_ensemble=LogisticRegression()
logit_ensemble.fit(enz,y_val)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [159]:
enz_pred_logit=logit_ensemble.predict(enz)

In [160]:
dmc_error(y_val, np.round(enz_pred_logit))

127171.0

In [166]:
logit_ensemble2=LogisticRegression()
logit_ensemble2.fit(enz[:170549],y_val[:170549])
enz_pred_logit2=logit_ensemble2.predict(enz[170549:])

dmc_error(y_val[170549:], np.round(enz_pred_logit2))

64914.0

In [167]:
64914*2

129828

In [168]:
logit_ensemble2=LogisticRegression()
logit_ensemble2.fit(enz[:255824],y_val[:255824])
enz_pred_logit2=logit_ensemble2.predict(enz[255824:])

dmc_error(y_val[255824:], np.round(enz_pred_logit2))

32896.0

In [169]:
32896*4

131584