In [14]:
from __future__ import division

label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from datetime import datetime
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn import linear_model
from sklearn import svm
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import confusion_matrix
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
#from sklearn.externals import joblib

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [3]:
df=pd.read_csv('train_gue.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2325165 entries, 0 to 2325164
Data columns (total 30 columns):
orderID             object
orderDate           object
articleID           object
colorCode           int64
sizeCode            object
productGroup        float64
quantity            int64
price               float64
rrp                 float64
voucherAmount       float64
customerID          object
paymentMethod       object
returnQuantity      int64
mmdd                object
months              int64
order_total         float64
customer_budget     float64
expense_ratio       float64
unit_price          float64
usual_unit_price    float64
price_diff          float64
after_voucher       float64
order_order         int64
choice_order        int64
articleID_prob      float64
colorCode_prob      float64
customerID_prob     float64
sizeCode_prob       float64
ac_prob             float64
as_prob             float64
dtypes: float64(17), int64(6), object(7)
memory usage: 532.2+ MB


In [5]:
object_columns=df.loc[:, df.dtypes == object].columns
df= df.drop(object_columns, axis=1)

In [6]:
#delete missing value

label='returnQuantity'

df=df.dropna()

Xdf=df.drop([label], axis=1)

X=Xdf.values
y=df.returnQuantity.values

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [18]:
rfr=RandomForestRegressor(n_jobs=-1)
rfr.fit(X_train, y_train)
y_pred=rfr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[109206  57972     23      1      0      0]
 [ 34575 146198    174      6      0      0]
 [    34    285    209      1      0      0]
 [     1      9      9     10      0      0]
 [     0      2      2      1      3      0]
 [     0      2      0      0      0      0]]
93185


In [19]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[116951  50236     15      0      0      0]
 [ 31761 149185      7      0      0      0]
 [     9    520      0      0      0      0]
 [     0     20      9      0      0      0]
 [     0      1      7      0      0      0]
 [     0      0      2      0      0      0]]
82644


In [34]:
#Bingung cara kerjanya, hasilnya kok bisa minus semua bisa positif semua (liat cell bawah)
#Outputnya kegedean

lr=SGDRegressor()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
# y_pred=np.array([round(yp) for yp in y_pred])
# y_pred[y_pred<0]=0
# print confusion_matrix(y_test,y_pred)
# print dmc_error(y_test,y_pred)

print y_pred.max()
print y_pred.min()
y_pred

-5.23286087183e+14
-7.64739702364e+15


array([ -8.63985010e+14,  -7.59925360e+15,  -1.68269137e+15, ...,
        -2.64156350e+15,  -2.47267293e+15,  -1.75171641e+15])

In [35]:
lr=SGDRegressor()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
# y_pred=np.array([round(yp) for yp in y_pred])
# y_pred[y_pred<0]=0
# print confusion_matrix(y_test,y_pred)
# print dmc_error(y_test,y_pred)

print y_pred.max()
print y_pred.min()
y_pred

1.23445806952e+15
1.13927893332e+14


array([  1.35105843e+14,   1.15211260e+15,   2.50059018e+14, ...,
         4.00105924e+14,   3.92787572e+14,   2.82114389e+14])

In [21]:
lr=linear_model.Ridge()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[116953  50234     15      0      0      0]
 [ 31762 149184      7      0      0      0]
 [     9    520      0      0      0      0]
 [     0     20      9      0      0      0]
 [     0      1      7      0      0      0]
 [     0      0      2      0      0      0]]
82643


In [22]:
lr=linear_model.BayesianRidge()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[116954  50233     15      0      0      0]
 [ 31761 149185      7      0      0      0]
 [     9    520      0      0      0      0]
 [     0     20      9      0      0      0]
 [     0      1      7      0      0      0]
 [     0      0      2      0      0      0]]
82641


In [23]:
lr=linear_model.Lasso()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[107548  59652      2      0      0      0]
 [ 75378 105575      0      0      0      0]
 [   146    383      0      0      0      0]
 [     6     23      0      0      0      0]
 [     2      6      0      0      0      0]
 [     1      1      0      0      0      0]]
135808
