In [1]:
label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [2]:
df=pd.read_csv('train_gue3.csv')

In [3]:
df = df[:1023297]

In [4]:
object_columns=df.loc[:, df.dtypes == object].columns
df= df.drop(object_columns, axis=1)

In [5]:
df= df.drop(['colorCode','productGroup','months','price','rrp','voucherAmount','after_voucher'], axis=1)

In [6]:
label='returnQuantity'

Xdf=df.drop([label], axis=1)

X=Xdf.values
y=df.returnQuantity.values

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[147407  15305      7      1      1      0]
 [ 13456 160924      5      0      0      0]
 [     1    538      5      0      0      0]
 [     0      7     23      0      0      0]
 [     0      0      4      0      0      0]
 [     0      0      5      0      0      0]]
29387


In [9]:
lr=linear_model.Lasso()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[106510  56206      5      0      0      0]
 [ 74670  99715      0      0      0      0]
 [   189    355      0      0      0      0]
 [    11     19      0      0      0      0]
 [     0      4      0      0      0      0]
 [     1      4      0      0      0      0]]
131723


In [10]:
lr=linear_model.Ridge()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[147400  15312      7      1      1      0]
 [ 13450 160930      5      0      0      0]
 [     1    538      5      0      0      0]
 [     0      7     23      0      0      0]
 [     0      0      4      0      0      0]
 [     0      0      5      0      0      0]]
29388


In [11]:
poly = PolynomialFeatures(2)
X = poly.fit_transform(X).astype(np.float32)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[146612  16101      7      1      0      0]
 [ 11733 162577     74      0      1      0]
 [     6    104    434      0      0      0]
 [     0      2      6     22      0      0]
 [     0      0      0      1      3      0]
 [     0      0      1      1      1      2]]
28061


In [14]:
lr=linear_model.Lasso()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[149394  13327      0      0      0      0]
 [ 21497 152885      3      0      0      0]
 [    66    474      4      0      0      0]
 [     2     26      2      0      0      0]
 [     0      4      0      0      0      0]
 [     0      4      1      0      0      0]]
35524


In [15]:
lr=linear_model.Ridge()
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[146615  16098      7      1      0      0]
 [ 11756 162555     73      0      1      0]
 [     6    104    434      0      0      0]
 [     0      2      6     22      0      0]
 [     0      0      0      1      3      0]
 [     0      0      1      1      1      2]]
28080


In [16]:
df.columns

Index([u'quantity', u'returnQuantity', u'order_total', u'customer_budget',
       u'expense_ratio', u'unit_price', u'usual_unit_price', u'price_diff',
       u'order_order', u'choice_order', u'articleID_cumprob',
       u'colorCode_cumprob', u'customerID_cumprob', u'sizeCode_cumprob',
       u'ac_cumprob', u'as_cumprob', u'cps_cumprob'],
      dtype='object')