In [2]:
label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from scipy import stats
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from operator import itemgetter

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [3]:
df=pd.read_csv('train_gue5.csv')

In [4]:
df.productGroup = df.productGroup.fillna('45')

In [5]:
X_train = df[:-341099]
y_train = df[label][:-341099]
X_test = df[-341099:]
y_test = df[label][-341099:]

In [8]:
probcols = [['articleID'],['articleID','colorCode'],['articleID','sizeCode'],['articleID','productGroup'],['articleID','customerID'],['articleID','deviceID'],['articleID','paymentMethod'],
            ['articleID','colorCode','productGroup'],['articleID','sizeCode','productGroup'],['articleID','productGroup','customerID'],['articleID','productGroup','deviceID'],['articleID','productGroup','paymentMethod'],
            ['articleID','sizeCode','customerID'],['articleID','colorCode','customerID'],['articleID','voucherID','customerID'],['articleID','productGroup','voucherID'],['articleID','voucherID'],['articleID','customerID','paymentMethod'],
            ['articleID','customerID','paymentMethod'],['articleID','customerID','deviceID'],['colorCode','sizeCode','customerID'],['colorCode','customerID'],['colorCode','voucherID','customerID'],['colorCode','voucherID','customerID'],
            ['colorCode','productGroup','customerID'],['colorCode','customerID','deviceID'],['colorCode','customerID','paymentMethod'],['deviceID','paymentMethod'],['paymentMethod'],['deviceID'],['articleID','colorCode','sizeCode'],
            ['sizeCode','customerID'],['customerID'],['customerID','deviceID'],['sizeCode','customerID','deviceID'],['productGroup'],['colorCode','sizeCode']]

for x in probcols:
    if len(x) == 1:
        dict_name = x[0] + '_cumprob'
    else:
        dict_name = ''
        for i in range(0,len(x)):
            dict_name = dict_name+ x[i][0]+ x[i][1]
        dict_name = dict_name + '_prob'
    y = list(x)
    y.append(dict_name)
    to_change = dict_name
    tmp = X_train.groupby(x)[y].last()
    dict_name = tmp[to_change].to_dict()
    del tmp
    
    if len(x) == 1:
        print 'changing ' + to_change
        X_test[to_change] = X_test[x[0]].apply(dict_name.get).replace(np.nan, 0.5).replace(np.inf, 0.5)
        del dict_name
    else :
        print 'changing ' + to_change
        X_test[to_change] = X_test[x].apply(tuple, axis=1).apply(dict_name.get).replace(np.nan, 0.5).replace(np.inf, 0.5)
        del dict_name  
    
    

changing articleID_cumprob


C:\Users\LENOVO\Anaconda2\lib\site-packages\ipykernel\__main__.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


changing arco_prob


C:\Users\LENOVO\Anaconda2\lib\site-packages\ipykernel\__main__.py:29: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


changing arsi_prob
changing arpr_prob
changing arcu_prob
changing arde_prob
changing arpa_prob
changing arcopr_prob
changing arsipr_prob
changing arprcu_prob
changing arprde_prob
changing arprpa_prob
changing arsicu_prob
changing arcocu_prob
changing arvocu_prob
changing arprvo_prob
changing arvo_prob
changing arcupa_prob
changing arcupa_prob
changing arcude_prob
changing cosicu_prob
changing cocu_prob
changing covocu_prob
changing covocu_prob
changing coprcu_prob
changing cocude_prob
changing cocupa_prob
changing depa_prob
changing paymentMethod_cumprob
changing deviceID_cumprob
changing arcosi_prob
changing sicu_prob
changing customerID_cumprob
changing cude_prob
changing sicude_prob
changing productGroup_cumprob
changing cosi_prob


In [10]:
tmp = [('unit_price', 1), ('median_unit_price', 1), ('price_diff', 1), ('articleID_cumprob', 1), ('arco_prob', 1), ('arsi_prob', 1), ('arpr_prob', 1), ('arcu_prob', 1), ('arde_prob', 1), ('arpa_prob', 1), ('arcopr_prob', 1), ('arsipr_prob', 1), ('arprcu_prob', 1), ('arprde_prob', 1), ('arprpa_prob', 1), ('voucherAmount', 2), ('order_total', 3), ('after_voucher', 4), ('arsicu_prob', 5), ('arcocu_prob', 6), ('quantity', 7), ('arvocu_prob', 8), ('arprvo_prob', 9), ('arvo_prob', 10), ('arcupa_prob', 11), ('arcude_prob', 12), ('cosicu_prob', 13), ('cocu_prob', 14), ('covocu_prob', 15), ('coprcu_prob', 16), ('cocude_prob', 17), ('cocupa_prob', 18), ('depa_prob', 19), ('paymentMethod_cumprob', 20), ('deviceID_cumprob', 21), ('arcosi_prob', 22), ('sicu_prob', 23), ('customerID_cumprob', 24), ('cude_prob', 25), ('sicude_prob', 26), ('productGroup_cumprob', 27), ('cosi_prob', 28), ('coside_prob', 29), ('prdepa_prob', 30), ('vocu_prob', 31), ('cupa_prob', 32), ('vocupa_prob', 33), ('sivocu_prob', 34), ('prpa_prob', 35), ('voucherID_cumprob', 36), ('prcu_prob', 37), ('prcude_prob', 38), ('vocude_prob', 39), ('cosivo_prob', 40), ('sizeCode_cumprob', 41), ('prvocu_prob', 42), ('cosipa_prob', 43), ('sicupa_prob', 44), ('arcode_prob', 45), ('siprcu_prob', 46), ('sipr_prob', 47), ('sipa_prob', 48), ('sidepa_prob', 49), ('colorCode_cumprob', 50), ('vopa_prob', 51), ('prvo_prob', 52), ('prvopa_prob', 53), ('arside_prob', 54), ('cudepa_prob', 55), ('side_prob', 56), ('siprpa_prob', 57), ('ardepa_prob', 58), ('copr_prob', 59), ('arvode_prob', 60), ('coprvo_prob', 61), ('arcovo_prob', 62), ('codepa_prob', 63), ('coprde_prob', 64), ('prcupa_prob', 65), ('arsivo_prob', 66), ('arsipa_prob', 67), ('copa_prob', 68), ('coprpa_prob', 69), ('siprde_prob', 70), ('arcopa_prob', 71), ('sivopa_prob', 72), ('sivode_prob', 73), ('price', 74), ('vodepa_prob', 75), ('vode_prob', 76), ('arvopa_prob', 77), ('covo_prob', 78), ('cosipr_prob', 79), ('code_prob', 80), ('prvode_prob', 81), ('expense_ratio', 82), ('choice_order', 83), ('covode_prob', 84), ('sivo_prob', 85), ('prde_prob', 86), ('deviceID', 87), ('rrp', 88), ('siprvo_prob', 89), ('covopa_prob', 90), ('order_order', 91), ('customer_budget', 92)]

didrop = [name for name,rank in tmp if rank>28]
X_train = X_train.drop(didrop, axis=1)
X_test = X_test.drop(didrop, axis=1)

object_columns=X_train.loc[:, df.dtypes == object].columns
X_train= X_train.drop(object_columns, axis=1)
X_train= X_train.drop(['colorCode'], axis=1)

X_test= X_test.drop(object_columns, axis=1)
X_test= X_test.drop(['colorCode'], axis=1)

In [11]:
label='returnQuantity'

Xx_train=X_train.drop([label], axis=1).values
Xx_test=X_test.drop([label], axis=1).values
yy_train=y_train.values
yy_test=y_test.values

In [14]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(Xx_train, yy_train)
y_pred=lr.predict(Xx_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(yy_test,y_pred)
print dmc_error(yy_test,y_pred)

[[123179  43636     73      0      0      0     31]
 [113741  59755     14      0      0      0      0]
 [     3    620      7      0      0      0      0]
 [     0     24      5      0      0      0      0]
 [     0      0      7      0      0      0      0]
 [     0      1      2      1      0      0      0]
 [     0      0      0      0      0      0      0]]
100752878151.0


In [18]:
rfr=RandomForestRegressor(n_jobs=-1)
rfr.fit(Xx_train, yy_train)
y_pred=lr.predict(Xx_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(yy_test,y_pred)
print dmc_error(yy_test,y_pred)

OverflowError: Python int too large to convert to C long

In [17]:
y_pred.min()

0

In [20]:
X_test.to_csv('X_test.csv')