## Notebook rilut

In [2]:
from __future__ import division

label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from operator import itemgetter
#from sklearn.externals import joblib

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

def feature_importances(Xdf, rf_model):
    pair=zip(Xdf.columns, rf_model.feature_importances_)
    t1=[i for i in pair]; t1
    return sorted(t1, key=itemgetter(1))

In [3]:
# Pakai make_datasets_train_only. Buat sendiri juga boleh

df=pd.read_csv('train_gue.csv')

if 'deviceID' in df.columns:
    del df['deviceID']

df.head()

customerID   orderID   orderDate articleID  colorCode sizeCode  \
0   c1000001  a1001465  2014-01-03  i1003077       3999        I   
1   c1000001  a1004977  2014-01-07  i1003082       1999        I   
2   c1000001  a1012517  2014-01-15  i1001229       1993       38   
3   c1000001  a1013536  2014-01-16  i1002531       1995       38   
4   c1000001  a1013536  2014-01-16  i1002531       1999       40   

   productGroup  quantity      price        rrp    ...     budget  \
0          17.0         1  27.984375  27.984375    ...     69.625   
1          17.0         1  25.984375  25.984375    ...     69.625   
2           4.0         1  40.000000  40.000000    ...     69.625   
3          15.0         1  60.000000  60.000000    ...     69.625   
4          15.0         1  60.000000  60.000000    ...     69.625   

  after_voucher  order_order choice_order  articleID_prob  colorCode_prob  \
0     27.984375            1            1        0.509766        0.510254   
1     25.984375            2            1        0.427734        0.522461   
2     40.000000            3            1        0.473145        0.471680   
3    120.000000            4            1        0.502930        0.541992   
4    120.000000            5            2        0.502930        0.522461   

   customerID_prob  sizeCode_prob   ac_prob   as_prob  
0         0.478516       0.374268  0.566265  0.566265  
1         0.478516       0.374268  0.456790  0.456790  
2         0.478516       0.535645  0.495726  0.495726  
3         0.478516       0.535645  0.438257  0.438257  
4         0.478516       0.529297  0.519280  0.519280  

[5 rows x 26 columns]

In [4]:
# Tambah metodemu di sini atau terserah di manapun!

# metodemu

In [5]:
#Konversi kategori/object ke angka (ordinal)
print "Konversi kategori/object ke angka (ordinal):"

#Cari kolom yang tipenya object, bukan integer maupun float
object_columns=df.loc[:, df.dtypes == object].columns

for col in object_columns:
    print col
    le=LabelEncoder()
    # Konversi deh
    df[col]=le.fit_transform(df[col])
    
if 'orderID' in df.columns:
    del df['orderID']

Konversi kategori/object ke angka (ordinal):
customerID
orderID
orderDate
articleID
sizeCode
paymentMethod
mmdd


In [6]:
# Turunin presisi, iseng-iseng aja
float_64_columns = df.loc[:, df.dtypes == np.float64].columns
for col in float_64_columns:
    df[col] = df[col].astype(np.float16)

int_64_columns = df.loc[:, df.dtypes == np.int64].columns
for col in int_64_columns:
    df[col] = df[col].astype(np.int32)
    

# Impute
df.rrp.fillna(df.rrp.median(), inplace=True)
df.productGroup.fillna(0, inplace=True)


Xdf=df.drop([label, "colorCode",'customerID'], axis=1)

X=Xdf.values
y=df.returnQuantity.values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [7]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[117425  50321     28      0      0      0]
 [ 32142 148225     13      0      0      0]
 [     6    557     23      0      0      0]
 [     0     11     14      0      0      0]
 [     0      1      3      1      0      0]
 [     0      0      4      1      0      0]]
83161


# 83213

In [8]:
# rfr=RandomForestRegressor(20, n_jobs=3)
# rfr.fit(X_train, y_train)
# y_pred_rfr=rfr.predict(X_test)
# y_pred_rfr=np.array([round(yp) for yp in y_pred_rfr], dtype=np.int8)
# y_pred_rfr[y_pred_rfr<0]=0
# print confusion_matrix(y_test,y_pred_rfr)
# print dmc_error(y_test,y_pred_rfr)

In [9]:
# feature_importances(Xdf, rfr)

In [10]:
# y_pred_ens=(1*rfr.predict(X_test) + 9*model.predict(X_test))/10
# y_pred_ens=np.array([round(yp) for yp in y_pred_ens], dtype=np.int8)
# y_pred_ens[y_pred_ens<0]=0
# print confusion_matrix(y_test,y_pred_ens)
# print dmc_error(y_test,y_pred_ens)

```

```