### Fitur-fitur hasil selesksi RFE

[('unit_price', 1),
 ('median_unit_price', 1),
 ('price_diff', 1),
 ('articleID_cumprob', 1),
 ('arco_prob', 1),
 ('arsi_prob', 1),
 ('arpr_prob', 1),
 ('arcu_prob', 1),
 ('arde_prob', 1),
 ('arpa_prob', 1),
 ('arcopr_prob', 1),
 ('arsipr_prob', 1),
 ('arprcu_prob', 1),
 ('arprde_prob', 1),
 ('arprpa_prob', 1),
 ('voucherAmount', 2),
 ('order_total', 3),
 ('after_voucher', 4),
 ('arsicu_prob', 5),
 ('arcocu_prob', 6),
 ('quantity', 7),
 ('arvocu_prob', 8),
 ('arprvo_prob', 9),
 ('arvo_prob', 10),
 ('arcupa_prob', 11),
 ('arcude_prob', 12),
 ('cosicu_prob', 13),
 ('cocu_prob', 14),
 ('covocu_prob', 15),
 ('coprcu_prob', 16),
 ('cocude_prob', 17),
 ('cocupa_prob', 18),
 ('depa_prob', 19),
 ('paymentMethod_cumprob', 20),
 ('deviceID_cumprob', 21),
 ('arcosi_prob', 22),
 ('sicu_prob', 23),
 ('customerID_cumprob', 24),
 ('cude_prob', 25),
 ('sicude_prob', 26),
 ('productGroup_cumprob', 27),
 ('cosi_prob', 28)]

In [1]:
label='returnQuantity'

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from scipy import stats
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from operator import itemgetter

def dmc_error(returnQuantity, prediction):
    #∑ |returnQuantity𝑖 − prediction𝑖 |
    return np.sum(np.abs( np.subtract(returnQuantity, prediction) ))

In [2]:
df=pd.read_csv('train_gue5.csv')

In [3]:
object_columns=df.loc[:, df.dtypes == object].columns
df= df.drop(object_columns, axis=1)

In [4]:
df= df.drop(['colorCode','productGroup'], axis=1)

In [5]:
df.rrp=df.rrp.fillna(df.rrp.median())

In [6]:
label='returnQuantity'

Xdf=df.drop([label], axis=1)

X=Xdf.values
y=df.returnQuantity.values

In [7]:
# Turunin presisi, iseng-iseng aja
float_64_columns = df.loc[:, df.dtypes == np.float64].columns
for col in float_64_columns:
    df[col] = df[col].astype(np.float32)

int_64_columns = df.loc[:, df.dtypes == np.int64].columns
for col in int_64_columns:
    df[col] = df[col].astype(np.int32)

In [8]:
# from sklearn.feature_selection import RFE
# lr=LinearRegression(n_jobs=-1, normalize=True)
# selector = RFE(lr, 28, step=1)
# selector = selector.fit(X, y)
# pair=zip(Xdf.columns, selector.ranking_)
# t1=[i for i in pair]; t1
# selector = RFE(lr, 5, step=1)
# Xrfe = selector.fit_transform(X, y)
# arai=sorted(t1, key=itemgetter(1)); arai

In [9]:
arai=[('unit_price', 1), ('median_unit_price', 1), ('price_diff', 1), ('articleID_cumprob', 1), ('arco_prob', 1), ('arsi_prob', 1), ('arpr_prob', 1), ('arcu_prob', 1), ('arde_prob', 1), ('arpa_prob', 1), ('arcopr_prob', 1), ('arsipr_prob', 1), ('arprcu_prob', 1), ('arprde_prob', 1), ('arprpa_prob', 1), ('voucherAmount', 2), ('order_total', 3), ('after_voucher', 4), ('arsicu_prob', 5), ('arcocu_prob', 6), ('quantity', 7), ('arvocu_prob', 8), ('arprvo_prob', 9), ('arvo_prob', 10), ('arcupa_prob', 11), ('arcude_prob', 12), ('cosicu_prob', 13), ('cocu_prob', 14), ('covocu_prob', 15), ('coprcu_prob', 16), ('cocude_prob', 17), ('cocupa_prob', 18), ('depa_prob', 19), ('paymentMethod_cumprob', 20), ('deviceID_cumprob', 21), ('arcosi_prob', 22), ('sicu_prob', 23), ('customerID_cumprob', 24), ('cude_prob', 25), ('sicude_prob', 26), ('productGroup_cumprob', 27), ('cosi_prob', 28), ('coside_prob', 29), ('prdepa_prob', 30), ('vocu_prob', 31), ('cupa_prob', 32), ('vocupa_prob', 33), ('sivocu_prob', 34), ('prpa_prob', 35), ('voucherID_cumprob', 36), ('prcu_prob', 37), ('prcude_prob', 38), ('vocude_prob', 39), ('cosivo_prob', 40), ('sizeCode_cumprob', 41), ('prvocu_prob', 42), ('cosipa_prob', 43), ('sicupa_prob', 44), ('arcode_prob', 45), ('siprcu_prob', 46), ('sipr_prob', 47), ('sipa_prob', 48), ('sidepa_prob', 49), ('colorCode_cumprob', 50), ('vopa_prob', 51), ('prvo_prob', 52), ('prvopa_prob', 53), ('arside_prob', 54), ('cudepa_prob', 55), ('side_prob', 56), ('siprpa_prob', 57), ('ardepa_prob', 58), ('copr_prob', 59), ('arvode_prob', 60), ('coprvo_prob', 61), ('arcovo_prob', 62), ('codepa_prob', 63), ('coprde_prob', 64), ('prcupa_prob', 65), ('arsivo_prob', 66), ('arsipa_prob', 67), ('copa_prob', 68), ('coprpa_prob', 69), ('siprde_prob', 70), ('arcopa_prob', 71), ('sivopa_prob', 72), ('sivode_prob', 73), ('price', 74), ('vodepa_prob', 75), ('vode_prob', 76), ('arvopa_prob', 77), ('covo_prob', 78), ('cosipr_prob', 79), ('code_prob', 80), ('prvode_prob', 81), ('expense_ratio', 82), ('choice_order', 83), ('covode_prob', 84), ('sivo_prob', 85), ('prde_prob', 86), ('deviceID', 87), ('rrp', 88), ('siprvo_prob', 89), ('covopa_prob', 90), ('order_order', 91), ('customer_budget', 92)]

In [10]:
#drop fitur yang rank nya > 28
#split training-test

didrop=[name for name,rank in arai if rank>28]
X2=Xdf.drop(didrop, axis=1).values
X_train = X2[:-341099]
y_train = y[:-341099]
X_test = X2[-341099:]
y_test = y[-341099:]

In [11]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[166097    817      5      0      0      0]
 [   197 173300     13      0      0      0]
 [     0    615     15      0      0      0]
 [     0      1     28      0      0      0]
 [     0      0      7      0      0      0]
 [     0      0      3      1      0      0]]
1707.0


# 1707

```
[[166097    817      5      0      0      0]
 [   197 173300     13      0      0      0]
 [     0    615     15      0      0      0]
 [     0      1     28      0      0      0]
 [     0      0      7      0      0      0]
 [     0      0      3      1      0      0]]
1707.0
```

In [12]:
rfr=RandomForestRegressor(n_jobs=-1)
rfr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[166097    817      5      0      0      0]
 [   197 173300     13      0      0      0]
 [     0    615     15      0      0      0]
 [     0      1     28      0      0      0]
 [     0      0      7      0      0      0]
 [     0      0      3      1      0      0]]
1707.0


In [13]:
etr=ExtraTreesRegressor(n_jobs=-1)
etr.fit(X_train, y_train)
y_pred=etr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)
print 'jumlah data test: ', len(y_test)

[[166784    134      1      0      0      0]
 [   315 173188      7      0      0      0]
 [     0     15    615      0      0      0]
 [     0      0      1     28      0      0]
 [     0      0      0      1      6      0]
 [     0      1      0      0      0      3]]
479.0
jumlah data test:  341099


In [28]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation

model = Sequential([
    Dense(42, input_dim=42),
    Activation('tanh'),
    Dense(1),
    #Activation('relu'),
])
model.compile(optimizer='rmsprop', loss='mae')

model.fit(X_train,y_train, nb_epoch=1,#verbose=0
         )

INFO (theano.gof.compilelock): Refreshing lock C:\Users\Lab Komputasi\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64\lock_dir\lock
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/Lab Komputasi/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpqv5jix/871c51ee977ba1fb8766e4f4db105247.lib and object C:/Users/Lab Komputasi/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpqv5jix/871c51ee977ba1fb8766e4f4db105247.exp

DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/Lab Komputasi/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpzvybc_/be6fee64e4c58ebeeefa177065293209.lib and object C:/Users/Lab Komputasi/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-6

Epoch 1/1
  78080/1984066 [>.............................] - ETA: 129s - loss: 0.0898

ValueError: I/O operation on closed file

In [21]:
X_train.shape

(1984066L, 42L)

In [ ]:
# logr=LogisticRegression(n_jobs=-1, solver='sag', max_iter=10)
# logr.fit(X_train, y_train)
# y_pred=etr.predict(X_test)
# y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
# y_pred[y_pred<0]=0
# print confusion_matrix(y_test,y_pred)
# print dmc_error(y_test,y_pred)
# print 'jumlah data test: ', len(y_test)

In [ ]:
#Fitur hasil RFE28 dibuat polynomial featuresnya
poly = PolynomialFeatures(2)
Xpoly = poly.fit_transform(X2).astype(np.float32)

Traceback (most recent call last):
  File "C:\Users\Lab Komputasi\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1118, in get_records


In [ ]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(np.log(X_train+1), np.log(y_train+1))
y_pred=np.exp(lr.predict(np.log(X_test)))-1
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

In [96]:
#df[['articleID_cumprob','colorCode_cumprob','arco_prob']]

In [23]:
X_train = Xpoly[:-341099]
y_train = y[:-341099]
X_test = Xpoly[-341099:]
y_test = y[-341099:]

In [24]:
lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

[[163451   3468      0      0      0      0]
 [ 10868 162642      0      0      0      0]
 [    33    597      0      0      0      0]
 [     3     26      0      0      0      0]
 [     0      7      0      0      0      0]
 [     1      3      0      0      0      0]]
15098.0


In [22]:
#coba pakai PCA 
from sklearn.decomposition import PCA

pca = PCA(n_components=25)
Xpca = pca.fit_transform(X2)

In [25]:
X_train = Xpca[:-341099]
y_train = y[:-341099]
X_test = Xpca[-341099:]
y_test = y[-341099:]

lr=LinearRegression(n_jobs=-1, normalize=True)
lr.fit(X_train, y_train)
y_pred=lr.predict(X_test)
y_pred=np.array([round(yp) for yp in y_pred], dtype=np.int8)
y_pred[y_pred<0]=0
print confusion_matrix(y_test,y_pred)
print dmc_error(y_test,y_pred)

# Lebih jelek karena fiturnya sudah diseleksi

[[165676   1237      6      0      0      0]
 [   324 173178      8      0      0      0]
 [     1    615     14      0      0      0]
 [     0      2     27      0      0      0]
 [     0      0      7      0      0      0]
 [     0      0      3      1      0      0]]
2254.0


In [97]:
def time_series_validation(n, step):
    """Cross validation for time-series data."""
    leap = 50000; k = 800000; h = 314099
    indices = np.arange(n)
    for i in range(step):
        yield indices[:k], indices[k:k+h]
        k += leap

In [99]:
def validation(X,y):
    """Local Cross Validation.
    """
    X_train= X
    y_train= y
    regress = LinearRegression(n_jobs=-1, normalize=True)

    print(" --- Start local evaluation.")
    tsv = time_series_validation(X_train.shape[0], 20)
    i=1; scores = []
    for train, test in tsv:
        size = test.shape[0]

        regress.fit(X_train[train], y_train[train])
        y_pred = regress.predict(X_train[test])
        y_pred = np.array([round(yp) for yp in y_pred], dtype=np.int8)
        y_pred[y_pred < 0] = 0

        y_true = y_train[test]
        
        score = dmc_error(y_true, y_pred)

        print(" ---- Score of #{0} : {1:.5f}".format(i, score))
        i += 1
        scores.append(score)

    print(" --- Finished local evaluation.")
    quantiles = stats.mstats.mquantiles(scores)
    print(" --- Score Results:")
    print(" - min: {:.5f}".format(np.min(scores)))
    print(" - 25%: {:.5f}".format(quantiles[0]))
    print(" - median: {:.5f}".format(np.median(scores)))
    print(" - 75%: {:.5f}".format(quantiles[2]))
    print(" - max: {:.5f}".format(np.max(scores)))
    print(" - mean: {0:.5f} (+/-{1:.5f})".format(np.mean(scores), stats.sem(scores)))

In [100]:
validation(X2.values,y)

 --- Start local evaluation.
 ---- Score of #1 : 1209.00000
 ---- Score of #2 : 1172.00000
 ---- Score of #3 : 1152.00000
 ---- Score of #4 : 1129.00000
 ---- Score of #5 : 1182.00000
 ---- Score of #6 : 1190.00000
 ---- Score of #7 : 1198.00000
 ---- Score of #8 : 1195.00000
 ---- Score of #9 : 1184.00000
 ---- Score of #10 : 1164.00000
 ---- Score of #11 : 1149.00000
 ---- Score of #12 : 1213.00000
 ---- Score of #13 : 1219.00000
 ---- Score of #14 : 1253.00000
 ---- Score of #15 : 1302.00000
 ---- Score of #16 : 1273.00000
 ---- Score of #17 : 1301.00000
 ---- Score of #18 : 1268.00000
 ---- Score of #19 : 1319.00000
 ---- Score of #20 : 1314.00000
 --- Finished local evaluation.
 --- Score Results:
 - min: 1129.00000
 - 25%: 1176.50000
 - median: 1203.50000
 - 75%: 1270.75000
 - max: 1319.00000
 - mean: 1219.30000 (+/-13.22082)


[('unit_price', 1),
 ('median_unit_price', 1),
 ('price_diff', 1),
 ('articleID_cumprob', 1),
 ('arco_prob', 1),
 ('arsi_prob', 1),
 ('arpr_prob', 1),
 ('arcu_prob', 1),
 ('arde_prob', 1),
 ('arpa_prob', 1),
 ('arcopr_prob', 1),
 ('arsipr_prob', 1),
 ('arprcu_prob', 1),
 ('arprde_prob', 1),
 ('arprpa_prob', 1),
 ('voucherAmount', 2),
 ('order_total', 3),
 ('after_voucher', 4),
 ('arsicu_prob', 5),
 ('arcocu_prob', 6),
 ('quantity', 7),
 ('arvocu_prob', 8),
 ('arprvo_prob', 9),
 ('arvo_prob', 10),
 ('arcupa_prob', 11),
 ('arcude_prob', 12),
 ('cosicu_prob', 13),
 ('cocu_prob', 14),
 ('covocu_prob', 15),
 ('coprcu_prob', 16),
 ('cocude_prob', 17),
 ('cocupa_prob', 18),
 ('depa_prob', 19),
 ('paymentMethod_cumprob', 20),
 ('deviceID_cumprob', 21),
 ('arcosi_prob', 22),
 ('sicu_prob', 23),
 ('customerID_cumprob', 24),
 ('cude_prob', 25),
 ('sicude_prob', 26),
 ('productGroup_cumprob', 27),
 ('cosi_prob', 28),
 ('coside_prob', 29),
 ('prdepa_prob', 30),
 ('vocu_prob', 31),
 ('cupa_prob', 32),
 ('vocupa_prob', 33),
 ('sivocu_prob', 34),
 ('prpa_prob', 35),
 ('voucherID_cumprob', 36),
 ('prcu_prob', 37),
 ('prcude_prob', 38),
 ('vocude_prob', 39),
 ('cosivo_prob', 40),
 ('sizeCode_cumprob', 41),
 ('prvocu_prob', 42),
 ('cosipa_prob', 43),
 ('sicupa_prob', 44),
 ('arcode_prob', 45),
 ('siprcu_prob', 46),
 ('sipr_prob', 47),
 ('sipa_prob', 48),
 ('sidepa_prob', 49),
 ('colorCode_cumprob', 50),
 ('vopa_prob', 51),
 ('prvo_prob', 52),
 ('prvopa_prob', 53),
 ('arside_prob', 54),
 ('cudepa_prob', 55),
 ('side_prob', 56),
 ('siprpa_prob', 57),
 ('ardepa_prob', 58),
 ('copr_prob', 59),
 ('arvode_prob', 60),
 ('coprvo_prob', 61),
 ('arcovo_prob', 62),
 ('codepa_prob', 63),
 ('coprde_prob', 64),
 ('prcupa_prob', 65),
 ('arsivo_prob', 66),
 ('arsipa_prob', 67),
 ('copa_prob', 68),
 ('coprpa_prob', 69),
 ('siprde_prob', 70),
 ('arcopa_prob', 71),
 ('sivopa_prob', 72),
 ('sivode_prob', 73),
 ('price', 74),
 ('vodepa_prob', 75),
 ('vode_prob', 76),
 ('arvopa_prob', 77),
 ('covo_prob', 78),
 ('cosipr_prob', 79),
 ('code_prob', 80),
 ('prvode_prob', 81),
 ('expense_ratio', 82),
 ('choice_order', 83),
 ('covode_prob', 84),
 ('sivo_prob', 85),
 ('prde_prob', 86),
 ('deviceID', 87),
 ('rrp', 88),
 ('siprvo_prob', 89),
 ('covopa_prob', 90),
 ('order_order', 91),
 ('customer_budget', 92)]